<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="gazebo.urdf.xacro" />
    <xacro:include filename="lidar.urdf.xacro" />
    <!--xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" /-->

    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="rod_radius" value="0.02"/>
    <xacro:property name="rod_height" value="0.8"/>
    <xacro:property name="screen_x" value="0.3"/>
    <xacro:property name="screen_y" value="0.4"/>
    <xacro:property name="screen_z" value="0.3"/>
    <xacro:property name="screen_back_x" value="0.1"/>
    <xacro:property name="screen_back_y" value="${screen_y - 0.1}"/>
    <xacro:property name="screen_back_z" value="${screen_z - 0.1}"/>
    <xacro:property name="screen_face_x" value="0.01"/>
    <xacro:property name="screen_face_y" value="${screen_y * 0.8}"/>
    <xacro:property name="screen_face_z" value="${screen_z * 0.8}"/>
    <xacro:property name="screen_face_line_thickness" value="${0.002}"/>
    <xacro:property name="wheel_radius" value="0.055"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.27"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
    <xacro:property name="mass" value="1.0"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="blue-gray_base">
        <color rgba="0.576 0.682 0.784 1"/>
    </material>

    <material name="gray__rod">
        <color rgba="0.263 0.357 0.341 1"/>
    </material>

    <material name="blue_screen">
        <color rgba="0.388 0.537 0.773 1"/>
    </material>

    <material name="green_screen_face_line">
        <color rgba="0.51 0.698 0.188 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.138" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name='chassis'>
    
    <inertial>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}" iyz="0.0"
                 izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}" />
    </inertial>
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="blue-gray_base"/>
    </visual>
    <collision>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Gray</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="rod_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rod"/>
        <origin xyz="${-chassis_length/3.5} 0 ${rod_height/2}" rpy="0 0 0" />
    </joint>

    <link name="rod">
        <visual>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
            <material name="gray__rod"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="screen_joint" type="continuous">
        <parent link="rod"/>
        <child link="screen"/>
        <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="screen">
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}" iyz="0.0"
                 izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}" />
    </inertial>
        <visual>
            <geometry>
                <box size="${screen_x} ${screen_y} ${screen_z}"/>
            </geometry>
            <material name="blue_screen"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="screen_back_joint" type="fixed">
        <parent link="screen"/>
        <child link="screen_back"/>
        <origin xyz="${-screen_x/2} 0 0" rpy="0 0 0" />
    </joint>

    <link name="screen_back">
        <visual>
            <geometry>
                <box size="${screen_back_x} ${screen_back_y} ${screen_back_z}"/>
            </geometry>
            <material name="blue_screen"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rod_radius}" length="${rod_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="screen_face_joint" type="fixed">
        <parent link="screen"/>
        <child link="screen_face"/>
        <origin xyz="${screen_x/2-0.002} 0 0" rpy="0 0 0" />
    </joint>

    <link name="screen_face">
        <visual>
            <geometry>
                <box size="${screen_face_x} ${screen_face_y} ${screen_face_z}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.01 ${screen_face_y} ${screen_face_z}"/>
            </geometry>
        </collision>
    </link>

    <joint name="screen_face_line_joint" type="fixed">
        <parent link="screen_face"/>
        <child link="screen_face_line"/>
        <origin xyz="0.0001 0 0" rpy="0 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="screen_face_line">
        <visual>
            <geometry>
                <box size="${screen_face_x} ${screen_face_y} ${screen_face_line_thickness}"/>
            </geometry>
            <material name="green_screen_face_line"/>
        </visual>
    </link>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>